# Generated by Django 4.2.10 on 2024-07-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoPet', models.CharField(max_length=50, verbose_name='Nome do PET')),
                ('raca', models.CharField(max_length=40, verbose_name='Raça')),
                ('tamanho', models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], verbose_name='Porte')),
                ('nomeDoTutor', models.CharField(max_length=80, verbose_name='Nome do TUTOR')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('data', models.DateTimeField(help_text='dd/mm/aaaa', verbose_name='Data')),
                ('turno', models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Turno')),
                ('observacoes', models.TextField(verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Reserva de Banho',
                'verbose_name_plural': 'Reservas de Banho',
            },
        ),
    ]
