# Generated by Django 4.2.10 on 2024-08-15 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_reserva_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(help_text='dd/mm/YYYY', verbose_name='DATA'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=5, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nomeDoPet',
            field=models.CharField(max_length=100, verbose_name='Nome do PET'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nomeDoTutor',
            field=models.CharField(max_length=100, verbose_name='Nome do TUTOR'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='raca',
            field=models.CharField(max_length=100, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tamanho',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=7, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
