# Generated by Django 4.2.10 on 2024-08-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_remove_reserva_turno_reserva_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='horario',
            field=models.TimeField(choices=[('oito', '08:00'), ('nove', '09:00'), ('dez', '10:00'), ('onze', '11:00'), ('treze', '13:00'), ('quatorze', '14:00'), ('quinze', '15:00'), ('dezesseis', '16:00')], default='--:--', verbose_name='Horário'),
        ),
    ]
